steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
  env:
  - 'GOOGLE_CLOUD_CREDENTIALS_PROJECT_ID=${_GOOGLE_CLOUD_CREDENTIALS_PROJECT_ID}'
  - 'GOOGLE_CLOUD_CREDENTIALS_CLIENT_EMAIL=${_GOOGLE_CLOUD_CREDENTIALS_CLIENT_EMAIL}'
  - 'GOOGLE_CLOUD_CREDENTIALS_PRIVATE_KEY=${_GOOGLE_CLOUD_CREDENTIALS_PRIVATE_KEY}'
