version: '2'
services:
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    container_name: "readto-api-postgres"
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    container_name: "readto-api-redis"

      # Port 6379 is used within the container, use that in your .env file
      # Port 6381 is opened on your host.

      # Use port 6381 to connect to Redis using a client
      # Use port 5432 to connect to Postgres using a client
