version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/playpost-api # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM depedencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build TypeScript
          command: npm run build
      - run: # run tests
          name: Run tests
          command: npm test
  deploy:
    working_directory: ~/playpost-api # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b2:b5:c6:86:73:74:38:eb:c7:42:6d:3b:84:c6:39:5c"
      - run: ssh-keyscan 142.93.227.22 >> ~/.ssh/known_hosts
      - run:
          name: Add dokku as remote branch
          command: git remote add dokku dokku@142.93.227.22:playpost-api-production # IP address as remote is used, as CloudFlare does not support ssh/git
      - run:
          name: Push to dokku production
          command: git push dokku master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
