version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/playpost-api # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM depedencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build TypeScript
          command: npm run build
      - run: # run tests
          name: Run tests
          command: npm test
deployment:
  production:
    branch: master
    commands:
      - git remote add dokku dokku@dokku-api.playpost.app:playpost-api-production
      - git push dokku master
