version: '2'
services:
  postgres:
    image: postgres:latest
    # env_file: .env
    environment:
    - POSTGRES_PASSWORD=playpostapi
    - POSTGRES_USER=playpostapi
    - POSTGRES_DB=d5sgoa8nt7dnim # So we can use a production dump locally
    ports:
      - "5432:5432"
    # volumes:
      # - ./dump:/docker-entrypoint-initdb.d
    container_name: "playpost-api-postgres"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: "playpost-api-redis"

      # Port 6379 is used within the container, use that in your .env file
      # Port 6381 is opened on your host.

      # Use port 6381 to connect to Redis using a client
      # Use port 5432 to connect to Postgres using a client
