export const articles = [
  {
    id: '84165aa1-5485-4e0b-a30d-23b49158e43c',
    title: '',
    description: '',
    url: '',
    languageCode: '',
    sourceName: '',
    imageUrl: '',
    readingTime: '',
    authorName: '',
    authorUrl: '',
    categoryName: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: ''
    },
    html: '',
    ssml: '',
    text: '',
  },
  {
    id: '59e5d709-004e-40aa-942f-f8d9e9f9cc53',
    title: '',
    description: '',
    url: '',
    languageCode: '',
    sourceName: '',
    imageUrl: '',
    readingTime: '',
    authorName: '',
    authorUrl: '',
    categoryName: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: ''
    },
    html: '',
    ssml: '',
    text: '',
  },
  {
    id: 'd8677a1d-644c-42d3-8df1-7e404ba6f5a6',
    title: '',
    description: '',
    url: '',
    languageCode: '',
    sourceName: '',
    imageUrl: '',
    readingTime: '',
    authorName: '',
    authorUrl: '',
    categoryName: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    user: {
      id: ''
    },
    html: '',
    ssml: '',
    text: '',
  }
]
